AreaEnglish/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

handler404 = 'home.views.error404'
handler500 = 'home.views.error500'

home/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path('register/', views.registerPage, name="register"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),

    path('password_change_done/', auth_views.PasswordChangeDoneView.as_view(template_name="pages/changePassSuccess.html"), name="password_change_done"),
    path('change_password/', auth_views.PasswordChangeView.as_view(template_name="pages/changePassword.html"), name="change_password"),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="pages/password.html"), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="pages/sendEmailSuccess.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="pages/newPassword.html"), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="pages/resetPassSuccess.html"), name="password_reset_complete"),

    path('', views.home, name="home"),

    # # Class 
    path('listclass/', views.listClass, name='listclass'),
    path('createclass/', views.createClass, name='createclass'),
    path('class/<int:pk>/', views.detailClass, name='detailclass'),
    path('classstudent/<int:pk>/', views.detailClassStudent, name='detailclassstudent'),
    path('checkinclassstudent/<int:pk>/', views.checkinClassStudent, name='checkinclassstudent'),

    # # Manager 
    path('createstafaccount/',views.createStafAccount,name='createstafaccount'),
    path('updateuser/<int:pk>',views.updateUser,name='updateuser'),
    path('editprofile/<str:pk>',views.editProfile,name='editprofile'),
    path('listuser/',views.listUser,name='listuser'),
    path('newroom/',views.newRoom,name='newroom'),
    path('editroom/<int:pk>',views.editRoom,name='editroom'),
    path('newarea/',views.newArea,name='newarea'),
    path('editarea/<int:pk>',views.editArea,name='editarea'),
    path('listarea/',views.listArea,name='listarea'),
    path('notify/',views.notify,name='notify'), 
    path('editnotify/<int:pk>',views.editNotify,name='editnotify'), 
    path('createtimeshift/',views.createTimeShift,name='createtimeshift'), 
    path('edittimeshift/<int:pk>',views.editTimeShift,name='edittimeshift'),
    path('createunit/',views.createUnit,name='createunit'), 
    path('editinformationunit/<int:pk>',views.editInformationUnit,name='editinformationunit'),
    # path('roleacount/',views.RoleAcount,name='roleacount'),
    # # Schedule 
    # path('createschedule/',views.CreateSchedule,name='createschedule'),
    # path('listschedule/',views.ListSchedule,name='listschedule'),
    # path('detailschedule/',views.DetailSchedule,name='detailschedule'),
    # Student 
    path('checkinstudent/<int:pk>/', views.checkinStudent, name='checkinstudent'),
    path('liststudent/', views.listStudent, name='liststudent'),
    path('createstudent', views.createStudent, name='createstudent'),
    path('student/<int:pk>/',views.detailStudent,name='detailstudent'),
    # path('createdetailschedule/<int:pk>/',views.createDetailSchedule,name='createdetailschedule'), 
    # # Teacher 
    path('createteacher/',views.createTeacher,name='createteacher'),
    path('listteacher/',views.listTeacher,name='listteacher'),
    path('teacher/<int:pk>/',views.detailTeacher,name='detailteacher'),

    path('contact/',views.contact, name='contact'),
    path('errorrole/',views.errorRole, name='errorrole'),

]

home/models.py
from django.db import models

# Create your models here.

class Gender(models.Model):
    name = models.CharField(max_length=5, verbose_name="Giới tính")

    def __str__(self):
        return  self.name
    class Meta:
        ordering =["name"]
        verbose_name_plural = "Giới tính"

class Area(models.Model):
    fullname = models.CharField(max_length=100, verbose_name="Tên cơ sở")
    phonenumber = models.CharField(max_length=100, null=True, blank=True, default="", verbose_name="SDT")
    email = models.CharField(max_length=100, null=True, blank=True, default="", verbose_name="Email")
    adress = models.CharField(max_length=300, null=True, blank=True, default="", verbose_name="Địa chỉ")
    note = models.CharField(max_length=300, null=True, blank=True, default="", verbose_name="Ghi chú")
    active = models.BooleanField(default=True, verbose_name="Trạng thái")

    def __str__(self):
        return  self.fullname
    class Meta:
        ordering =["fullname"]
        verbose_name_plural = "Chi nhánh"

class Unit(models.Model):
    fullname = models.CharField(max_length=100, verbose_name="Tên khóa học")
    infomation = models.CharField(max_length=1000, blank=True, null=True, verbose_name="Thông tin khóa học")
    fee = models.IntegerField(default=0, verbose_name="Học phí khóa học")
    active = models.BooleanField(default=True, verbose_name="Trạng thái")

    def __str__(self):
        return  self.fullname
    class Meta:
        ordering =["fullname"]
        verbose_name_plural = "Khóa học"

class TimeShift(models.Model):
    fullname = models.CharField(max_length=100, verbose_name="Tên ca học")
    infomation = models.CharField(max_length=1000, blank=True, verbose_name="Thông tin ca học")
    timestart = models.TimeField(null = True, blank=True, verbose_name="Giờ bắt đầu")
    timeend = models.TimeField(null = True, blank=True, verbose_name="Giờ kết thúc")
    active = models.BooleanField(default=True, verbose_name="Trạng thái")
    
    def __str__(self):
        return  self.fullname
    class Meta:
        ordering =["fullname"]
        verbose_name_plural = "Ca học"

class TimeWeek(models.Model):
    name = models.CharField(max_length=100, verbose_name="Loại")

    def __str__(self):
        return  self.name
    class Meta:
        ordering =["name"]
        verbose_name_plural = "Ngày học trong tuần"

class Room(models.Model):
    fullname = models.CharField(max_length=100, verbose_name="Tên phòng")
    area = models.ForeignKey(Area, null= True, on_delete=models.SET_NULL)
    active = models.BooleanField(default=True, verbose_name="Trạng thái")

    def __str__(self):
        return  self.fullname
    class Meta:
        ordering =["fullname"]
        verbose_name_plural = "Phòng"

class Teacher(models.Model):
    fullname = models.CharField(max_length=100, verbose_name="Tên giáo viên")
    gender = models.ForeignKey(Gender, null= True, on_delete=models.SET_NULL)
    birthday = models.DateField(verbose_name="Ngày sinh")
    identity_card = models.CharField(max_length=100, null = True, blank=True, verbose_name="CMND")
    phonenumber = models.CharField(max_length=100, null = True, blank=True, verbose_name="SDT")
    email = models.CharField(max_length=100, null = True, blank=True, verbose_name="Email")
    adress = models.CharField(max_length=300, null = True, blank=True, verbose_name="Địa chỉ")
    create_date = models.DateField(auto_now_add=True, verbose_name="Ngày tạo thông tin")
    note = models.CharField(max_length=300, null = True, blank=True, verbose_name="Ghi chú")
    active = models.BooleanField(default=True, verbose_name="Trạng thái")

    def __str__(self):
        return  self.fullname
    class Meta:
        ordering =["fullname"]
        verbose_name_plural = "Giáo viên"

class Classname(models.Model):
    fullname = models.CharField(max_length=100, verbose_name="Tên lớp học")
    startdate = models.DateField(auto_now_add=True, verbose_name="Ngày bắt đầu")
    room = models.ForeignKey(Room, null= True, on_delete=models.SET_NULL)
    unit = models.ForeignKey(Unit, null = True, on_delete=models.SET_NULL)
    timeshift = models.ForeignKey(TimeShift, null = True, on_delete=models.SET_NULL)
    startdate = models.DateField(verbose_name="Ngày bắt đầu học")
    timeweek = models.ForeignKey(TimeWeek, null = True, on_delete=models.SET_NULL)
    teacher = models.ForeignKey(Teacher, null = True, on_delete=models.SET_NULL)
    datecount = models.IntegerField(default=0, blank=True, verbose_name="Số buổi học")
    note = models.CharField(max_length=300, null = True, blank=True, verbose_name="Ghi chú")
    active = models.BooleanField(default=True, verbose_name="Trạng thái")

    def __str__(self):
        return  self.fullname
    class Meta:
        ordering =["fullname"]
        verbose_name_plural = "Lớp học"
                
class Student(models.Model):
    fullname = models.CharField(max_length=100, verbose_name="Tên học sinh")
    gender = models.ForeignKey(Gender, null= True, on_delete=models.SET_NULL)
    birthday = models.DateField(verbose_name="Ngày sinh")
    identity_card = models.CharField(max_length=100, null = True, blank=True, verbose_name="CMND")
    phonenumber = models.CharField(max_length=100, null = True, blank=True, verbose_name="SDT")
    phonenumber_family = models.CharField(max_length=100, null = True, blank=True, verbose_name="SDT phụ huynh")
    email = models.CharField(max_length=100, null = True, blank=True, verbose_name="Email")
    adress = models.CharField(max_length=300, null = True, blank=True, verbose_name="Địa chỉ")
    classname = models.ForeignKey(Classname, null= True, on_delete=models.SET_NULL)
    fee = models.IntegerField(default=0, verbose_name="Học phí")
    fee_remain = models.IntegerField(default=0, verbose_name="Học phí còn lại")
    create_date = models.DateField(auto_now_add=True, verbose_name="Ngày đăng ký học")
    havedetailschedule = active = models.BooleanField(default=False, verbose_name="Thời khóa biểu cá nhân")
    note = models.CharField(max_length=300, null = True, blank=True, verbose_name="Ghi chú")
    active = models.BooleanField(default=True, verbose_name="Trạng thái")

    def __str__(self):
        return  self.fullname
    class Meta:
        ordering =["fullname"]
        verbose_name_plural = "Học sinh"

class Schedule(models.Model):
    id_classname = models.CharField(max_length=50, blank=True, null=True, verbose_name="ID học viên")
    classname = models.CharField(max_length=50, blank=True, null=True, verbose_name="Tên lớp")
    dayname = models.CharField(max_length=50, blank=True, null=True, verbose_name="Buổi")
    daylearn = models.DateField(verbose_name="Ngày học")
    timelearnstart = models.TimeField(null = True, blank=True,verbose_name="Thời gian học")
    timelearnend = models.TimeField(null = True, blank=True,verbose_name="Thời gian kết thúc")
    note = models.CharField(max_length=300, null = True, blank=True, verbose_name="Ghi chú")
    active = models.BooleanField(default=True, verbose_name="Trạng thái")
    
    def __str__(self):
        return  self.classname
    class Meta:
        ordering =["classname"]
        verbose_name_plural = "Lịch học theo lớp"

class CheckInClass(models.Model):
    id_student = models.IntegerField(default=0, blank=True, null=True, verbose_name="ID học viên")
    student = models.CharField(max_length=50, blank=True, null=True, verbose_name="Tên học viên")
    classname = models.CharField(max_length=50, blank=True, null=True, verbose_name="Tên lớp")
    dayname = models.CharField(max_length=50, blank=True, null=True, verbose_name="Buổi")
    daylearn = models.DateField(verbose_name="Ngày học")
    timelearnstart = models.TimeField(null = True, blank=True,verbose_name="Thời gian học")
    timelearnend = models.TimeField(null = True, blank=True,verbose_name="Thời gian kết thúc")
    note = models.CharField(max_length=300, null = True, blank=True, verbose_name="Ghi chú")
    active = models.BooleanField(default=True, verbose_name="Trạng thái")
    
    def __str__(self):
        return  self.student
    class Meta:
        ordering =["student"]
        verbose_name_plural = "Thời khóa biểu cá nhân"

class Notify(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True, verbose_name="Tiêu đề")
    content = models.CharField(max_length=1000, blank=True, null=True, verbose_name="Nội dung")
    create_date = models.DateField(auto_now_add=True, verbose_name="Ngày đăng")
    active = models.BooleanField(default=True, verbose_name="Trạng thái")

    def __str__(self):
        return  self.title
    class Meta:
        ordering =["title"]
        verbose_name_plural = "Thông báo"

home/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from .models import *

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','first_name','last_name','password1','password2','is_staff','is_superuser','is_active']

class CreateStudentForm(ModelForm):
    class Meta:
        model = Student
        fields = '__all__'

class UpdateStudentForm(ModelForm):
    class Meta:
        model = Student 
        fields = 'email','phonenumber','adress','phonenumber_family','fee','fee_remain','note','active'

class CreateClassnameForm(ModelForm):
    class Meta:
        model = Classname
        fields = '__all__'
        
class UpdateClassForm(ModelForm):
    class Meta:
        model = Classname
        fields = 'teacher','note','active'

class CreateTeacherForm(ModelForm):
    class Meta:
        model = Teacher
        fields = '__all__'
        
class UpdateTeacherForm(ModelForm):
    class Meta:
        model = Teacher
        fields = 'email','phonenumber','adress','note','active'

class CreateRoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'

class CreateAreaForm(ModelForm):
    class Meta:
        model = Area
        fields = '__all__'
        
class CreateNotifyForm(ModelForm):
    class Meta:
        model = Notify
        fields = '__all__'     

class CreateTimeShiftForm(ModelForm):
    class Meta:
        model = TimeShift
        fields = '__all__'

class CreateUnitForm(ModelForm):
    class Meta:
        model = Unit
        fields = '__all__'

home/templates/manager/editArea.html
{% extends "pages/base.html" %}
{% block title %}
<!-- Student -->
{% endblock title %}
{% block content %}
{% load static %}
<div class="container" style="padding-bottom: 3em;">
    <div class="row justify-content-center">
        <div class="col-lg-12">
            <div class="card shadow-lg border-0 rounded-lg mt-5">
                <div class="card-header">
                    <h3 class="text-center font-weight-light my-4">Chỉnh sửa thông tin chi nhánh</h3>
                </div>
                <div class="card-body">
                    <form action="" method="POST">
                        {% csrf_token %}
                        <!-- {{ form }} -->
                        <div class="row">
                            <div class="col-xl-6 col-md-12">
                                <div class="row">
                                    <div class="col-xl-6 col-md-12">
                                        <div class="form-group">
                                            <label class="small mb-1" for="id_fullname">Tên chi nhánh:</label>
                                            <input class="form-control" type="text" name="fullname" maxlength="100"
                                                value="{{ area.fullname }}" required="" id="id_fullname"
                                                placeholder="Nhập tên chi nhánh">
                                        </div>
                                    </div>
                                    <div class="col-xl-6 col-md-12">
                                        <div class="form-group">
                                            <label class="small mb-1" for="id_phonenumber">Số điện thoại chi
                                                nhánh:</label>
                                            <input class="form-control" type="text" name="phonenumber" maxlength="100"
                                                value="{{ area.phonenumber }}" id="id_phonenumber"
                                                placeholder="Nhập số điện thoại chi nhánh" />
                                        </div>
                                    </div>
                                    <div class="col-xl-12 col-md-12">
                                        <div class="form-group">
                                            <label class="small mb-1" for="inputEmailAddress">Email:</label>
                                            <input class="form-control" type="text" name="email" maxlength="100"
                                                value="{{ area.email }}" id="id_email"
                                                placeholder="Nhập email chi nhánh" />
                                        </div>
                                    </div>
                                    <div class="col-xl-12 col-md-12">
                                        <div class="form-group">
                                            <label class="small mb-1" for="inputEmailAddress">Địa chỉ:</label>
                                            <input class="form-control" type="text" name="adress" maxlength="300"
                                                value="{{ area.adress }}" id="id_adress"
                                                placeholder="Nhập địa chỉ chi nhánh" />
                                        </div>
                                    </div>
                                    <div class="col-xl-10 col-md-10">
                                        <div class="form-group">
                                            <label class="small mb-1" for="inputEmailAddress">Ghi chú:</label>
                                            <input class="form-control" type="text" name="note" maxlength="300"
                                                value="{{ area.note }}" id="id_note" placeholder="Nhập ghi chú" />
                                        </div>
                                    </div>
                                    <div class="col-xl-2 col-md-2">
                                        <div class="form-group">
                                            <label class="small mb-1" for="inputEmailAddress">Trạng thái:</label>
                                            {% if area.active %}
                                            <input type="checkbox" name="active" id="id_active" checked
                                                data-toggle="toggle" data-on="Mở" data-off="Đóng" data-onstyle="success"
                                                data-offstyle="danger" />
                                            {% else %}
                                            <input type="checkbox" name="active" id="id_active" data-toggle="toggle"
                                                data-on="Mở" data-off="Đóng" data-onstyle="success"
                                                data-offstyle="danger" />
                                            {% endif %}
                                        </div>
                                    </div>

                                </div>
                            </div>
                            <div class="col-xl-6 col-md-12">
                                <div class="col-xl-12 col-md-12">
                                    <table id="example" class="table" style="width:100%">
                                        <thead class="thead-dark">
                                            <tr>
                                                <th style="width: 30%;">ID phòng</th>
                                                <th style="width: 40%;">Tên phòng</th>
                                                <th style="width: 30%;">Trạng thái</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for i in room %}
                                            {% if i.area_id == area.pk %}
                                            <tr>
                                                <td>
                                                    <a class="btn btn-warning" style="width: 100%;" href="/editroom/{{i.pk}}">{{i.pk}}</a>
                                                </td>
                                                <td>{{i.fullname}}</td>
                                                {% if i.active %}
                                                <td style="text-align: center;"><i style="color: green;"
                                                        class="fas fa-check-circle"></i></td>
                                                {% else %}
                                                <td style="text-align: center;"><i style="color: red;"
                                                        class="fas fa-times-circle"></i></td>
                                                {% endif %}
                                            </tr>
                                            {% endif %}
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        
                        <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                            <input class="btn btn-success" type="submit" value="Cập nhật"
                                style="margin-left: auto; margin-right: auto;">
                                <a href="/newroom/" class="btn btn-success"
                                style="margin-left: auto; margin-right: auto;">Thêm phòng</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

home/templates/manager/editTimeShift.html
{% extends "pages/base.html" %}
<!-- break -->
{% block title %}
<!-- Student -->
{% endblock title %}
<!-- break -->
{% block content %}
<!-- break -->
{% load static %}
<!-- break -->
<div class="container" style="height: 52em;">
    <div class="row justify-content-center">
        <div class="col-lg-5">
            <div class="card shadow-lg border-0 rounded-lg mt-5">
                <div class="card-header">
                    <h3 class="text-center font-weight-light my-4">Sửa ca học</h3>
                </div>
                <div class="card-body">
                    <form action="" method="POST">
                        {% csrf_token %}
                        <!-- {{form}} -->
                        <div class="row">
                            <div class="col-xl-12 col-md-12">
                                <div class="form-group">
                                    <label class="small mb-1" for="id_fullname">Ca học</label>
                                    <input class="form-control" type="text" name="fullname" maxlength="100" required
                                        id="id_fullname" placeholder="Nhập tên ca học" value="{{timeshift.fullname}}" />
                                </div>
                            </div>
                            <div class="col-xl-12 col-md-12">
                                <div class="form-group">
                                    <label class="small mb-1" for="id_infomation">Thông tin chi tiết</label>
                                    <textarea class="form-control" name="infomation" maxlength="1000" id="id_infomation"
                                        rows="2" placeholder="Nội dung">{{timeshift.infomation}}</textarea>
                                </div>
                            </div>
                            <div class="col-xl-6 col-md-12">
                                <div class="form-group">
                                    <label class="small mb-1" for="id_timestart">Thời gian bắt đầu</label>
                                    <input class="form-control" type="time" name="timestart" id="id_timestart"
                                        value="{{timeshift.timestart|date:"H:i"}}" />
                                </div>
                            </div>
                            <div class="col-xl-6 col-md-12">
                                <div class="form-group">
                                    <label class="small mb-1" for="id_timeend">Thời gian kết thúc</label>
                                    <input class="form-control" type="time" name="timeend" id="id_timeend"
                                        value="{{timeshift.timeend|date:"H:i"}}" />
                                </div>
                            </div>
                            <div class="col-xl-12 col-md-12">
                                <label class="small mb-1" for="id_active">Trạng thái</label>
                                <div class="form-group">
                                    {% if timeshift.active %}
                                    <input type="checkbox" name="active" id="id_active" checked data-toggle="toggle"
                                        data-on="Hiễn thị" data-off="Ẩn" data-onstyle="success"
                                        data-offstyle="danger" />
                                    {% else %}
                                    <input type="checkbox" name="active" id="id_active" data-toggle="toggle"
                                        data-on="Hiễn thị" data-off="Ẩn" data-onstyle="success"
                                        data-offstyle="danger" />
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                            <input class="btn btn-primary" type="submit" value="Cập nhật"
                                style="margin-left: auto; margin-right: auto;">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- break -->
{% endblock content %}

home/templates/manager/newArea.html
{% extends "pages/base.html" %}
<!-- break -->
{% block title %}
<!-- Student -->
{% endblock title %}
<!-- break -->
{% block content %}
<!-- break -->
{% load static %}
<!-- break -->
<div class="container" style="height: 52em;">
    <div class="row justify-content-center">
        <div class="col-lg-10">
            <div class="card shadow-lg border-0 rounded-lg mt-5">
                <div class="card-header">
                    <h3 class="text-center font-weight-light my-4">Tạo thông tin chi nhánh mới</h3>
                </div>
                <div class="card-body">
                    <form action="" method="POST">
                        {% csrf_token %}
                        <!-- {{ form }} -->
                        <div class="row">
                            <div class="col-xl-6 col-md-12">
                                <div class="form-group">
                                    <label class="small mb-1" for="id_fullname">Tên chi nhánh:</label>
                                    <input class="form-control py-4" type="text" name="fullname" maxlength="100"
                                        required="" id="id_fullname" placeholder="Nhập tên chi nhánh mới">
                                </div>
                            </div>
                            <div class="col-xl-6 col-md-12">
                                <div class="form-group">
                                    <label class="small mb-1" for="id_phonenumber">Số điện thoại chi nhánh:</label>
                                    <input class="form-control py-4" type="text" name="phonenumber" maxlength="100"
                                        id="id_phonenumber" placeholder="Nhập số điện thoại chi nhánh" />
                                </div>
                            </div>
                            <div class="col-xl-12 col-md-12">
                                <div class="form-group">
                                    <label class="small mb-1" for="inputEmailAddress">Email:</label>
                                    <input class="form-control py-4" type="text" name="email" maxlength="100"
                                        id="id_email" placeholder="Nhập email chi nhánh" />
                                </div>
                            </div>
                            <div class="col-xl-12 col-md-12">
                                <div class="form-group">
                                    <label class="small mb-1" for="inputEmailAddress">Địa chỉ:</label>
                                    <input class="form-control py-4" type="text" name="adress" maxlength="300"
                                        id="id_adress" placeholder="Nhập địa chỉ chi nhánh" />
                                </div>
                            </div>
                            <div class="col-xl-10 col-md-10">
                                <div class="form-group">
                                    <label class="small mb-1" for="inputEmailAddress">Ghi chú:</label>
                                    <input class="form-control py-4" type="text" name="note" maxlength="300"
                                        id="id_note" placeholder="Nhập ghi chú" />
                                </div>
                            </div>
                            <div class="col-xl-2 col-md-2">
                                <div class="form-group">
                                    <label class="small mb-1" for="inputEmailAddress">Trạng thái:</label>
                                    <input type="checkbox" name="active" id="id_active" checked data-toggle="toggle"
                                        data-on="Mở" data-off="Đóng" data-onstyle="success" data-offstyle="danger" />
                                </div>
                            </div>
                        </div>
                        <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                            <input class="btn btn-primary" type="submit" value="Tạo phòng"
                                style="margin-left: auto; margin-right: auto;">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

home/templates/manager/roleAcount.html
{% extends "pages/base.html" %} {% block title %}
<!-- Student -->{% endblock title %} {% block content %} {% load static %} {% endblock content %}