AreaEnglish/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

handler404 = 'home.views.error404'
handler500 = 'home.views.error500'

home/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path('register/', views.registerPage, name="register"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),

    path('password_change_done/', auth_views.PasswordChangeDoneView.as_view(template_name="pages/changePassSuccess.html"), name="password_change_done"),
    path('change_password/', auth_views.PasswordChangeView.as_view(template_name="pages/changePassword.html"), name="change_password"),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="pages/password.html"), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="pages/sendEmailSuccess.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="pages/newPassword.html"), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="pages/resetPassSuccess.html"), name="password_reset_complete"),

    path('', views.home, name="home"),

    # # Class 
    path('listclass/', views.listClass, name='listclass'),
    path('createclass/', views.createClass, name='createclass'),
    path('class/<int:pk>/', views.detailClass, name='detailclass'),
    path('classstudent/<int:pk>/', views.detailClassStudent, name='detailclassstudent'),
    path('checkinclassstudent/<int:pk>/', views.checkinClassStudent, name='checkinclassstudent'),

    # # Manager 
    path('createstafaccount/',views.createStafAccount,name='createstafaccount'),
    path('updateuser/<int:pk>',views.updateUser,name='updateuser'),
    path('editprofile/<str:pk>',views.editProfile,name='editprofile'),
    path('listuser/',views.listUser,name='listuser'),
    path('newroom/',views.newRoom,name='newroom'),
    path('editroom/<int:pk>',views.editRoom,name='editroom'),
    path('newarea/',views.newArea,name='newarea'),
    path('editarea/<int:pk>',views.editArea,name='editarea'),
    path('listarea/',views.listArea,name='listarea'),
    path('notify/',views.notify,name='notify'), 
    path('editnotify/<int:pk>',views.editNotify,name='editnotify'), 
    path('createtimeshift/',views.createTimeShift,name='createtimeshift'), 
    path('edittimeshift/<int:pk>',views.editTimeShift,name='edittimeshift'),
    path('createunit/',views.createUnit,name='createunit'), 
    path('editinformationunit/<int:pk>',views.editInformationUnit,name='editinformationunit'),
    # path('roleacount/',views.RoleAcount,name='roleacount'),
    # # Schedule 
    # path('createschedule/',views.CreateSchedule,name='createschedule'),
    # path('listschedule/',views.ListSchedule,name='listschedule'),
    # path('detailschedule/',views.DetailSchedule,name='detailschedule'),
    # Student 
    path('checkinstudent/<int:pk>/', views.checkinStudent, name='checkinstudent'),
    path('liststudent/', views.listStudent, name='liststudent'),
    path('createstudent', views.createStudent, name='createstudent'),
    path('student/<int:pk>/',views.detailStudent,name='detailstudent'),
    # path('createdetailschedule/<int:pk>/',views.createDetailSchedule,name='createdetailschedule'), 
    # # Teacher 
    path('createteacher/',views.createTeacher,name='createteacher'),
    path('listteacher/',views.listTeacher,name='listteacher'),
    path('teacher/<int:pk>/',views.detailTeacher,name='detailteacher'),

    path('contact/',views.contact, name='contact'),
    path('errorrole/',views.errorRole, name='errorrole'),

]

home/models.py
from django.db import models

# Create your models here.

class Gender(models.Model):
    name = models.CharField(max_length=5, verbose_name="Giới tính")

    def __str__(self):
        return  self.name
    class Meta:
        ordering =["name"]
        verbose_name_plural = "Giới tính"

class Area(models.Model):
    fullname = models.CharField(max_length=100, verbose_name="Tên cơ sở")
    phonenumber = models.CharField(max_length=100, null=True, blank=True, default="", verbose_name="SDT")
    email = models.CharField(max_length=100, null=True, blank=True, default="", verbose_name="Email")
    adress = models.CharField(max_length=300, null=True, blank=True, default="", verbose_name="Địa chỉ")
    note = models.CharField(max_length=300, null=True, blank=True, default="", verbose_name="Ghi chú")
    active = models.BooleanField(default=True, verbose_name="Trạng thái")

    def __str__(self):
        return  self.fullname
    class Meta:
        ordering =["fullname"]
        verbose_name_plural = "Chi nhánh"

class Unit(models.Model):
    fullname = models.CharField(max_length=100, verbose_name="Tên khóa học")
    infomation = models.CharField(max_length=1000, blank=True, null=True, verbose_name="Thông tin khóa học")
    fee = models.IntegerField(default=0, verbose_name="Học phí khóa học")
    active = models.BooleanField(default=True, verbose_name="Trạng thái")

    def __str__(self):
        return  self.fullname
    class Meta:
        ordering =["fullname"]
        verbose_name_plural = "Khóa học"

class TimeShift(models.Model):
    fullname = models.CharField(max_length=100, verbose_name="Tên ca học")
    infomation = models.CharField(max_length=1000, blank=True, verbose_name="Thông tin ca học")
    timestart = models.TimeField(null = True, blank=True, verbose_name="Giờ bắt đầu")
    timeend = models.TimeField(null = True, blank=True, verbose_name="Giờ kết thúc")
    active = models.BooleanField(default=True, verbose_name="Trạng thái")
    
    def __str__(self):
        return  self.fullname
    class Meta:
        ordering =["fullname"]
        verbose_name_plural = "Ca học"

class TimeWeek(models.Model):
    name = models.CharField(max_length=100, verbose_name="Loại")

    def __str__(self):
        return  self.name
    class Meta:
        ordering =["name"]
        verbose_name_plural = "Ngày học trong tuần"

class Room(models.Model):
    fullname = models.CharField(max_length=100, verbose_name="Tên phòng")
    area = models.ForeignKey(Area, null= True, on_delete=models.SET_NULL)
    active = models.BooleanField(default=True, verbose_name="Trạng thái")

    def __str__(self):
        return  self.fullname
    class Meta:
        ordering =["fullname"]
        verbose_name_plural = "Phòng"

class Teacher(models.Model):
    fullname = models.CharField(max_length=100, verbose_name="Tên giáo viên")
    gender = models.ForeignKey(Gender, null= True, on_delete=models.SET_NULL)
    birthday = models.DateField(verbose_name="Ngày sinh")
    identity_card = models.CharField(max_length=100, null = True, blank=True, verbose_name="CMND")
    phonenumber = models.CharField(max_length=100, null = True, blank=True, verbose_name="SDT")
    email = models.CharField(max_length=100, null = True, blank=True, verbose_name="Email")
    adress = models.CharField(max_length=300, null = True, blank=True, verbose_name="Địa chỉ")
    create_date = models.DateField(auto_now_add=True, verbose_name="Ngày tạo thông tin")
    note = models.CharField(max_length=300, null = True, blank=True, verbose_name="Ghi chú")
    active = models.BooleanField(default=True, verbose_name="Trạng thái")

    def __str__(self):
        return  self.fullname
    class Meta:
        ordering =["fullname"]
        verbose_name_plural = "Giáo viên"

class Classname(models.Model):
    fullname = models.CharField(max_length=100, verbose_name="Tên lớp học")
    startdate = models.DateField(auto_now_add=True, verbose_name="Ngày bắt đầu")
    room = models.ForeignKey(Room, null= True, on_delete=models.SET_NULL)
    unit = models.ForeignKey(Unit, null = True, on_delete=models.SET_NULL)
    timeshift = models.ForeignKey(TimeShift, null = True, on_delete=models.SET_NULL)
    startdate = models.DateField(verbose_name="Ngày bắt đầu học")
    timeweek = models.ForeignKey(TimeWeek, null = True, on_delete=models.SET_NULL)
    teacher = models.ForeignKey(Teacher, null = True, on_delete=models.SET_NULL)
    datecount = models.IntegerField(default=0, blank=True, verbose_name="Số buổi học")
    note = models.CharField(max_length=300, null = True, blank=True, verbose_name="Ghi chú")
    active = models.BooleanField(default=True, verbose_name="Trạng thái")

    def __str__(self):
        return  self.fullname
    class Meta:
        ordering =["fullname"]
        verbose_name_plural = "Lớp học"
                
class Student(models.Model):
    fullname = models.CharField(max_length=100, verbose_name="Tên học sinh")
    gender = models.ForeignKey(Gender, null= True, on_delete=models.SET_NULL)
    birthday = models.DateField(verbose_name="Ngày sinh")
    identity_card = models.CharField(max_length=100, null = True, blank=True, verbose_name="CMND")
    phonenumber = models.CharField(max_length=100, null = True, blank=True, verbose_name="SDT")
    phonenumber_family = models.CharField(max_length=100, null = True, blank=True, verbose_name="SDT phụ huynh")
    email = models.CharField(max_length=100, null = True, blank=True, verbose_name="Email")
    adress = models.CharField(max_length=300, null = True, blank=True, verbose_name="Địa chỉ")
    classname = models.ForeignKey(Classname, null= True, on_delete=models.SET_NULL)
    fee = models.IntegerField(default=0, verbose_name="Học phí")
    fee_remain = models.IntegerField(default=0, verbose_name="Học phí còn lại")
    create_date = models.DateField(auto_now_add=True, verbose_name="Ngày đăng ký học")
    havedetailschedule = active = models.BooleanField(default=False, verbose_name="Thời khóa biểu cá nhân")
    note = models.CharField(max_length=300, null = True, blank=True, verbose_name="Ghi chú")
    active = models.BooleanField(default=True, verbose_name="Trạng thái")

    def __str__(self):
        return  self.fullname
    class Meta:
        ordering =["fullname"]
        verbose_name_plural = "Học sinh"

class Schedule(models.Model):
    id_classname = models.CharField(max_length=50, blank=True, null=True, verbose_name="ID học viên")
    classname = models.CharField(max_length=50, blank=True, null=True, verbose_name="Tên lớp")
    dayname = models.CharField(max_length=50, blank=True, null=True, verbose_name="Buổi")
    daylearn = models.DateField(verbose_name="Ngày học")
    timelearnstart = models.TimeField(null = True, blank=True,verbose_name="Thời gian học")
    timelearnend = models.TimeField(null = True, blank=True,verbose_name="Thời gian kết thúc")
    note = models.CharField(max_length=300, null = True, blank=True, verbose_name="Ghi chú")
    active = models.BooleanField(default=True, verbose_name="Trạng thái")
    
    def __str__(self):
        return  self.classname
    class Meta:
        ordering =["classname"]
        verbose_name_plural = "Lịch học theo lớp"

class CheckInClass(models.Model):
    id_student = models.IntegerField(default=0, blank=True, null=True, verbose_name="ID học viên")
    student = models.CharField(max_length=50, blank=True, null=True, verbose_name="Tên học viên")
    classname = models.CharField(max_length=50, blank=True, null=True, verbose_name="Tên lớp")
    dayname = models.CharField(max_length=50, blank=True, null=True, verbose_name="Buổi")
    daylearn = models.DateField(verbose_name="Ngày học")
    timelearnstart = models.TimeField(null = True, blank=True,verbose_name="Thời gian học")
    timelearnend = models.TimeField(null = True, blank=True,verbose_name="Thời gian kết thúc")
    note = models.CharField(max_length=300, null = True, blank=True, verbose_name="Ghi chú")
    active = models.BooleanField(default=True, verbose_name="Trạng thái")
    
    def __str__(self):
        return  self.student
    class Meta:
        ordering =["student"]
        verbose_name_plural = "Thời khóa biểu cá nhân"

class Notify(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True, verbose_name="Tiêu đề")
    content = models.CharField(max_length=1000, blank=True, null=True, verbose_name="Nội dung")
    create_date = models.DateField(auto_now_add=True, verbose_name="Ngày đăng")
    active = models.BooleanField(default=True, verbose_name="Trạng thái")

    def __str__(self):
        return  self.title
    class Meta:
        ordering =["title"]
        verbose_name_plural = "Thông báo"

home/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from .models import *

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','first_name','last_name','password1','password2','is_staff','is_superuser','is_active']

class CreateStudentForm(ModelForm):
    class Meta:
        model = Student
        fields = '__all__'

class UpdateStudentForm(ModelForm):
    class Meta:
        model = Student 
        fields = 'email','phonenumber','adress','phonenumber_family','fee','fee_remain','note','active'

class CreateClassnameForm(ModelForm):
    class Meta:
        model = Classname
        fields = '__all__'
        
class UpdateClassForm(ModelForm):
    class Meta:
        model = Classname
        fields = 'teacher','note','active'

class CreateTeacherForm(ModelForm):
    class Meta:
        model = Teacher
        fields = '__all__'
        
class UpdateTeacherForm(ModelForm):
    class Meta:
        model = Teacher
        fields = 'email','phonenumber','adress','note','active'

class CreateRoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'

class CreateAreaForm(ModelForm):
    class Meta:
        model = Area
        fields = '__all__'
        
class CreateNotifyForm(ModelForm):
    class Meta:
        model = Notify
        fields = '__all__'     

class CreateTimeShiftForm(ModelForm):
    class Meta:
        model = TimeShift
        fields = '__all__'

class CreateUnitForm(ModelForm):
    class Meta:
        model = Unit
        fields = '__all__'

home/templates/class/checkinClass.html
{% extends "pages/base.html" %} 
<!-- break -->
{% block title %}
<!-- Student -->
{% endblock title %} 
<!-- break -->
{% block content %} 
<!-- break -->
{% load static %} 
<!-- break -->

<!-- break -->
{% endblock content %}

home/templates/class/checkinClassStudent.html
{% extends "pages/base.html" %}
<!-- break -->
{% block title %}
<!-- Student -->
{% endblock title %}
<!-- break -->
{% block content %}
<!-- break -->
{% load static %}
<!-- break -->
<div class="card-header">
    <h2 class="text-center font-weight-light">Danh sách lớp</h2>
</div>
<div class="card-body">
    <form action="" method="POST">
        {% csrf_token %}
        <table id="example" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th style="width: 15%;">Tên học viên</th>
                    {% for i in schedule %}
                    {% if classname.fullname == i.classname %}
                    <th>{{ i.dayname }}</th>
                    {% endif %}
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                {% for i in liststudentinclass %}
                {% if i.classname_id == classname.pk %}
                {% if i.havedetailschedule%}
                <tr>
                    <td>{{ i.fullname}}</td>
                    {% for z in checkinclass %}
                    {% if i.pk == z.id_student %}
                    {% if z.active %}
                    <th>
                        <input type="checkbox" checked name="check" value="{{ z.pk }}">
                    </th>
                    {% else %}
                    <th>
                        <input type="checkbox" name="check" value="{{ z.pk }}">
                    </th>
                    {% endif %}

                    {% endif %}
                    {% endfor %}
                </tr>
                {% endif %}
                {% endif %}
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <th>Name</th>
                    {% for i in schedule %}
                    {% if classname.fullname == i.classname %}
                    <th>{{ i.daylearn|date:"d-m" }}</th>
                    {% endif %}
                    {% endfor %}
                </tr>
            </tfoot>
        </table>
        <button class="btn btn-success" type="submit">
            điểm danh
        </button>
    </form>
</div>
<!-- break -->
{% endblock content %}

home/templates/class/createClass.html
{% extends "pages/base.html" %}
<!-- break -->
{% block title %}
<!-- Student -->
{% endblock title %}
<!-- break -->
{% block content %}
<!-- break -->
{% load static %}
<!-- break -->
<div class="card-header">
    <h2 class="text-center font-weight-light">Mở lớp học mới</h2>
</div>
<div class="card-body">
    <form action="" method="POST">
        {% csrf_token %}
        <!-- {{form}} -->
        <div class="form-row">
            <div class="col-md-3">
                <label class="small mb-1" for="">Tên lớp</label>
                <div class="form-group">
                    <input class="form-control" maxlength="100" name="fullname" required id="id_fullname" type="text"
                        placeholder="Nhập tên lớp" />
                </div>
            </div>
            <div class="col-md-3">
                <label class="small mb-1" for="">Khóa học</label>
                <div class="form-group">
                    <select class="form-control" name="unit" required id="id_unit">
                        <!-- <option value="4" hidden>D</option> -->
                        {% for i in unit %}
                        {% if i.active %}
                        <option value="{{ i.pk }}">{{ i.fullname }}</option>
                        {% endif %}
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="col-md-3">
                <label class="small mb-1" for="">Giảng viên</label>
                <div class="form-group">
                    <select class="form-control" name="teacher" required id="id_teacher">
                        <!-- <option value="4" hidden>teacher</option> -->
                        {% for i in teacher %}
                        {% if i.active %}
                        <option value="{{ i.pk }}">{{ i.fullname }}</option>
                        {% endif %}
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="col-md-3">
                <label class="small mb-1" for="">Chi nhánh</label>
                <div class="form-group">
                    <select onchange="selectionAreaRoom(this.value)" class="form-control" name="area" required
                        id="id_area">
                        <!-- <option value="2" hidden>U</option> -->
                        {% for i in area %}
                        {% if i.active %}
                        <option value="{{ i.pk }}">{{ i.fullname }}</option>
                        {% endif %}
                        {% endfor %}
                    </select>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="col-md-2">
                <label class="small mb-1" for="">Ca học</label>
                <div class="form-group">
                    <select class="form-control" name="timeshift" required id="id_timeshift">
                        {% for i in timeshift %}
                        {% if i.active %}
                        <option value="{{ i.pk }}">{{ i.fullname }}</option>
                        {% endif %}
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="col-md-2">
                <label class="small mb-1" for="">Tuần học</label>
                <div class="form-group">
                    <select class="form-control" name="timeweek" required id="id_timeweek">
                        <!-- <option value="2" hidden>3-5-7</option> -->
                        {% for i in timeweek %}
                        <option value="{{ i.pk }}">{{ i.name }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="col-md-2">
                <label class="small mb-1" for="">Phòng</label>
                <div class="form-group">
                    <select class="form-control" name="room" required id="id_room">
                        {% for i in room %}
                        {% if i.active %}
                        <option value="{{ i.pk }}" data-option="{{i.area_id}}">{{ i.fullname }}</option>
                        {% endif %}
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="col-md-2">
                <label class="small mb-1" for="id_startdate">Ngày bắt đầu</label>
                <div class="form-group">
                    <input class="form-control" required name="startdate" id="id_startdate" type="date"/>
                </div>
            </div>
            <div class="col-md-2">
                <label class="small mb-1" for="inputNote">Ghi chú</label>
                <div class="form-group">
                    <input class="form-control" name="note" id="id_note" type="text" placeholder="Ghi chú" />
                </div>
            </div>
            <div class="col-md-1">
                <label class="small mb-1" for="id_datecount">Số buổi</label>
                <div class="form-group">
                    <input class="form-control" required name="datecount" id="id_datecount" type="number"
                        min="1" placeholder="Số buổi" />
                </div>
            </div>
            <div class="col-md-1">
                <label class="small mb-1" for="inputActive">Trạng thái</label>
                <div class="form-group">
                    <input type="checkbox" disabled name="active" id="id_active" data-toggle="toggle" data-on="Học"
                        data-off="Nghỉ" data-onstyle="success" data-offstyle="danger">
                </div>
            </div>
        </div>
        <script>
            var id_area = document.querySelector('#id_area');
            var id_room = document.querySelector('#id_room');
            var options_area_room = id_room.querySelectorAll('option');

            function selectionAreaRoom(selValue) {
                id_room.innerHTML = '';
                for (var i = 0; i < options_area_room.length; i++) {
                    if (options_area_room[i].dataset.option === selValue) {
                        id_room.appendChild(options_area_room[i]);
                    }
                }
            }
            document.getElementById('id_startdate').min = new Date(new Date().getTime() + 1000*60*60*24 ).toISOString().split("T")[0];
            selectionAreaRoom(id_area.value);
            
        </script>
        <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
            <input type="submit" value="Tạo lớp mới" class="btn btn-primary"
                style="margin-left: auto; margin-right: auto;">
        </div>
    </form>
</div>
<script src="{% static '/js/sweetalert.min.js' %}"></script>
<script src="{% static '/js/moment.min.js' %}"></script>
<script src="{% static '/js/jquery-3.4.1.min.js' %}"></script>
<!-- break -->
{% endblock content %}

home/templates/class/detailClass.html
{% extends "pages/base.html" %}
<!-- break -->
{% block title %}
<!-- Student -->
{% endblock title %}
<!-- break -->
{% block content %}
<!-- break -->
{% load static %}
<!-- break -->
<div class="card-header">
    <h2 class="text-center font-weight-light">Thông tin lớp học</h2>
</div>
<div class="card-body">
    <form action="" method="POST">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-md-3">
                <label class="small mb-1" for="">Tên lớp</label>
                <div class="form-group">
                    <input class="form-control" disabled maxlength="100" name="fullname" required id="id_fullname" type="text" placeholder="Tên lớp tự hiễn thị" value="{{ classname.fullname }}" />
                </div>
            </div>
            <div class="col-md-3">
                <label class="small mb-1" for="">Khóa học</label>
                <div class="form-group">
                    <input class="form-control" disabled id="" type="text" value="{{ classname.unit }}" />
                </div>
            </div>
            <div class="col-md-3">
                <label class="small mb-1" for="">Giảng viên</label>
                <div class="form-group">
                    <select class="form-control" name="teacher" required id="id_teacher">
                        <option value="{{ classname.teacher_id }}" hidden>{{ classname.teacher }}</option>
                        {% for i in teacher %}
                        {% if i.active %}
                            <option value="{{ i.pk }}">{{ i.fullname }}</option>
                        {% endif %}
                        {% endfor %}
                        </select>
                </div>
            </div>
            <div class="col-md-3">
                <label class="small mb-1" for="">Chi nhánh</label>
                <div class="form-group">
                    <select onchange="selectionAreaRoom(this.value)" class="form-control" name="area" required id="id_area" disabled>
                        {% for i in area %}
                        {% if i.active %}
                            <option value="{{i.pk}}">{{ i.fullname }}</option>
                        {% endif %}
                        {% endfor %}
                        </select>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="col-md-2">
                <label class="small mb-1" for="">Ca học</label>
                <div class="form-group">
                    <select class="form-control" name="timeshift" required id="id_timeshift" disabled>
                        {% for i in timeshift %}
                        {% if i.active %}
                            <option value="{{ i.pk }}">{{ i.fullname }}</option>
                        {% endif %}
                        {% endfor %}
                        </select>
                </div>
            </div>
            <div class="col-md-2">
                <label class="small mb-1" for="">Tuần học</label>
                <div class="form-group">
                    <select class="form-control" name="timeweek" required id="id_timeweek" disabled>
                        {% for i in timeweek %}
                            <option value="{{ i.pk }}">{{ i.name }}</option>
                        {% endfor %}
                        </select>
                </div>
            </div>
            <div class="col-md-2">
                <label class="small mb-1" for="">Phòng</label>
                <div class="form-group">
                    <select class="form-control" name="room" required id="id_room" disabled>
                        {% for i in room %}
                        {% if i.active %}
                            <option value="{{ i.pk }}" data-option="{{i.area_id}}">{{ i.fullname }}</option>
                        {% endif %}
                        {% endfor %}
                        </select>
                </div>
            </div>
            <div class="col-md-2">
                <label class="small mb-1" for="id_startdate">Ngày bắt đầu</label>
                <div class="form-group">
                    <input class="form-control" name="startdate" disabled id="id_startdate" value="{{classname.startdate|date:"Y-m-d"}}" type="date" />
                </div>
            </div>
            <div class="col-md-2">
                <label class="small mb-1" for="inputNote">Ghi chú</label>
                <div class="form-group">
                    <input class="form-control" name="note" id="id_note" value="{{classname.note}}" type="text" placeholder="Ghi chú" />
                </div>
            </div>
            <div class="col-md-1">
                <label class="small mb-1" for="id_datecount">Số buổi</label>
                <div class="form-group">
                    <input class="form-control" required disabled name="datecount" id="id_datecount" value="{{classname.datecount}}" type="number" min="0" placeholder="Số buổi" />
                </div>
            </div>
            <div class="col-md-1">
                <label class="small mb-1" for="inputActive">Trạng thái</label>
                <div class="form-group">
                    {% if classname.active %}
                        <input type="checkbox" disabled id="id_active" name="active" checked data-toggle="toggle" value="1" data-on="Học" data-off="Nghỉ" data-onstyle="success" data-offstyle="danger"> 
                    {% else %}
                        <input type="checkbox" disabled id="id_active" name="active" data-toggle="toggle" value="0" data-on="Học" data-off="Nghỉ" data-onstyle="success" data-offstyle="danger">
                    {% endif %}
                </div>
            </div>
            <script>
                var id_area = document.querySelector('#id_area');
                var id_room = document.querySelector('#id_room');
                var options_area_room = id_room.querySelectorAll('option');

                function selectionAreaRoom(selValue) {
                    id_room.innerHTML = '';
                    for (var i = 0; i < options_area_room.length; i++) {
                        if (options_area_room[i].dataset.option === selValue) {
                            id_room.appendChild(options_area_room[i]);
                        }
                    }
                }
                selectionAreaRoom(id_area.value);
            </script>
        </div>
        <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
            <input type="submit" value="Cập nhật lớp" class="btn btn-primary" style="margin-left: auto; margin-right: auto;">
        </div>
    </form>
</div>
<script src="{% static '/js/sweetalert.min.js' %}"></script>
<script src="{% static '/js/moment.min.js' %}"></script>
<script src="{% static '/js/jquery-3.4.1.min.js' %}"></script>
<!-- break -->
{% endblock content %}