AreaEnglish/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

handler404 = 'home.views.error404'
handler500 = 'home.views.error500'

home/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path('register/', views.registerPage, name="register"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),

    path('password_change_done/', auth_views.PasswordChangeDoneView.as_view(template_name="pages/changePassSuccess.html"), name="password_change_done"),
    path('change_password/', auth_views.PasswordChangeView.as_view(template_name="pages/changePassword.html"), name="change_password"),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="pages/password.html"), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="pages/sendEmailSuccess.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="pages/newPassword.html"), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="pages/resetPassSuccess.html"), name="password_reset_complete"),

    path('', views.home, name="home"),

    # # Class 
    path('listclass/', views.listClass, name='listclass'),
    path('createclass/', views.createClass, name='createclass'),
    path('class/<int:pk>/', views.detailClass, name='detailclass'),
    path('classstudent/<int:pk>/', views.detailClassStudent, name='detailclassstudent'),
    path('checkinclassstudent/<int:pk>/', views.checkinClassStudent, name='checkinclassstudent'),

    # # Manager 
    path('createstafaccount/',views.createStafAccount,name='createstafaccount'),
    path('updateuser/<int:pk>',views.updateUser,name='updateuser'),
    path('editprofile/<str:pk>',views.editProfile,name='editprofile'),
    path('listuser/',views.listUser,name='listuser'),
    path('newroom/',views.newRoom,name='newroom'),
    path('editroom/<int:pk>',views.editRoom,name='editroom'),
    path('newarea/',views.newArea,name='newarea'),
    path('editarea/<int:pk>',views.editArea,name='editarea'),
    path('listarea/',views.listArea,name='listarea'),
    path('notify/',views.notify,name='notify'), 
    path('editnotify/<int:pk>',views.editNotify,name='editnotify'), 
    path('createtimeshift/',views.createTimeShift,name='createtimeshift'), 
    path('edittimeshift/<int:pk>',views.editTimeShift,name='edittimeshift'),
    path('createunit/',views.createUnit,name='createunit'), 
    path('editinformationunit/<int:pk>',views.editInformationUnit,name='editinformationunit'),
    # path('roleacount/',views.RoleAcount,name='roleacount'),
    # # Schedule 
    # path('createschedule/',views.CreateSchedule,name='createschedule'),
    # path('listschedule/',views.ListSchedule,name='listschedule'),
    # path('detailschedule/',views.DetailSchedule,name='detailschedule'),
    # Student 
    path('checkinstudent/<int:pk>/', views.checkinStudent, name='checkinstudent'),
    path('liststudent/', views.listStudent, name='liststudent'),
    path('createstudent', views.createStudent, name='createstudent'),
    path('student/<int:pk>/',views.detailStudent,name='detailstudent'),
    # path('createdetailschedule/<int:pk>/',views.createDetailSchedule,name='createdetailschedule'), 
    # # Teacher 
    path('createteacher/',views.createTeacher,name='createteacher'),
    path('listteacher/',views.listTeacher,name='listteacher'),
    path('teacher/<int:pk>/',views.detailTeacher,name='detailteacher'),

    path('contact/',views.contact, name='contact'),
    path('errorrole/',views.errorRole, name='errorrole'),

]

home/models.py
from django.db import models

# Create your models here.

class Gender(models.Model):
    name = models.CharField(max_length=5, verbose_name="Giới tính")

    def __str__(self):
        return  self.name
    class Meta:
        ordering =["name"]
        verbose_name_plural = "Giới tính"

class Area(models.Model):
    fullname = models.CharField(max_length=100, verbose_name="Tên cơ sở")
    phonenumber = models.CharField(max_length=100, null=True, blank=True, default="", verbose_name="SDT")
    email = models.CharField(max_length=100, null=True, blank=True, default="", verbose_name="Email")
    adress = models.CharField(max_length=300, null=True, blank=True, default="", verbose_name="Địa chỉ")
    note = models.CharField(max_length=300, null=True, blank=True, default="", verbose_name="Ghi chú")
    active = models.BooleanField(default=True, verbose_name="Trạng thái")

    def __str__(self):
        return  self.fullname
    class Meta:
        ordering =["fullname"]
        verbose_name_plural = "Chi nhánh"

class Unit(models.Model):
    fullname = models.CharField(max_length=100, verbose_name="Tên khóa học")
    infomation = models.CharField(max_length=1000, blank=True, null=True, verbose_name="Thông tin khóa học")
    fee = models.IntegerField(default=0, verbose_name="Học phí khóa học")
    active = models.BooleanField(default=True, verbose_name="Trạng thái")

    def __str__(self):
        return  self.fullname
    class Meta:
        ordering =["fullname"]
        verbose_name_plural = "Khóa học"

class TimeShift(models.Model):
    fullname = models.CharField(max_length=100, verbose_name="Tên ca học")
    infomation = models.CharField(max_length=1000, blank=True, verbose_name="Thông tin ca học")
    timestart = models.TimeField(null = True, blank=True, verbose_name="Giờ bắt đầu")
    timeend = models.TimeField(null = True, blank=True, verbose_name="Giờ kết thúc")
    active = models.BooleanField(default=True, verbose_name="Trạng thái")
    
    def __str__(self):
        return  self.fullname
    class Meta:
        ordering =["fullname"]
        verbose_name_plural = "Ca học"

class TimeWeek(models.Model):
    name = models.CharField(max_length=100, verbose_name="Loại")

    def __str__(self):
        return  self.name
    class Meta:
        ordering =["name"]
        verbose_name_plural = "Ngày học trong tuần"

class Room(models.Model):
    fullname = models.CharField(max_length=100, verbose_name="Tên phòng")
    area = models.ForeignKey(Area, null= True, on_delete=models.SET_NULL)
    active = models.BooleanField(default=True, verbose_name="Trạng thái")

    def __str__(self):
        return  self.fullname
    class Meta:
        ordering =["fullname"]
        verbose_name_plural = "Phòng"

class Teacher(models.Model):
    fullname = models.CharField(max_length=100, verbose_name="Tên giáo viên")
    gender = models.ForeignKey(Gender, null= True, on_delete=models.SET_NULL)
    birthday = models.DateField(verbose_name="Ngày sinh")
    identity_card = models.CharField(max_length=100, null = True, blank=True, verbose_name="CMND")
    phonenumber = models.CharField(max_length=100, null = True, blank=True, verbose_name="SDT")
    email = models.CharField(max_length=100, null = True, blank=True, verbose_name="Email")
    adress = models.CharField(max_length=300, null = True, blank=True, verbose_name="Địa chỉ")
    create_date = models.DateField(auto_now_add=True, verbose_name="Ngày tạo thông tin")
    note = models.CharField(max_length=300, null = True, blank=True, verbose_name="Ghi chú")
    active = models.BooleanField(default=True, verbose_name="Trạng thái")

    def __str__(self):
        return  self.fullname
    class Meta:
        ordering =["fullname"]
        verbose_name_plural = "Giáo viên"

class Classname(models.Model):
    fullname = models.CharField(max_length=100, verbose_name="Tên lớp học")
    startdate = models.DateField(auto_now_add=True, verbose_name="Ngày bắt đầu")
    room = models.ForeignKey(Room, null= True, on_delete=models.SET_NULL)
    unit = models.ForeignKey(Unit, null = True, on_delete=models.SET_NULL)
    timeshift = models.ForeignKey(TimeShift, null = True, on_delete=models.SET_NULL)
    startdate = models.DateField(verbose_name="Ngày bắt đầu học")
    timeweek = models.ForeignKey(TimeWeek, null = True, on_delete=models.SET_NULL)
    teacher = models.ForeignKey(Teacher, null = True, on_delete=models.SET_NULL)
    datecount = models.IntegerField(default=0, blank=True, verbose_name="Số buổi học")
    note = models.CharField(max_length=300, null = True, blank=True, verbose_name="Ghi chú")
    active = models.BooleanField(default=True, verbose_name="Trạng thái")

    def __str__(self):
        return  self.fullname
    class Meta:
        ordering =["fullname"]
        verbose_name_plural = "Lớp học"
                
class Student(models.Model):
    fullname = models.CharField(max_length=100, verbose_name="Tên học sinh")
    gender = models.ForeignKey(Gender, null= True, on_delete=models.SET_NULL)
    birthday = models.DateField(verbose_name="Ngày sinh")
    identity_card = models.CharField(max_length=100, null = True, blank=True, verbose_name="CMND")
    phonenumber = models.CharField(max_length=100, null = True, blank=True, verbose_name="SDT")
    phonenumber_family = models.CharField(max_length=100, null = True, blank=True, verbose_name="SDT phụ huynh")
    email = models.CharField(max_length=100, null = True, blank=True, verbose_name="Email")
    adress = models.CharField(max_length=300, null = True, blank=True, verbose_name="Địa chỉ")
    classname = models.ForeignKey(Classname, null= True, on_delete=models.SET_NULL)
    fee = models.IntegerField(default=0, verbose_name="Học phí")
    fee_remain = models.IntegerField(default=0, verbose_name="Học phí còn lại")
    create_date = models.DateField(auto_now_add=True, verbose_name="Ngày đăng ký học")
    havedetailschedule = active = models.BooleanField(default=False, verbose_name="Thời khóa biểu cá nhân")
    note = models.CharField(max_length=300, null = True, blank=True, verbose_name="Ghi chú")
    active = models.BooleanField(default=True, verbose_name="Trạng thái")

    def __str__(self):
        return  self.fullname
    class Meta:
        ordering =["fullname"]
        verbose_name_plural = "Học sinh"

class Schedule(models.Model):
    id_classname = models.CharField(max_length=50, blank=True, null=True, verbose_name="ID học viên")
    classname = models.CharField(max_length=50, blank=True, null=True, verbose_name="Tên lớp")
    dayname = models.CharField(max_length=50, blank=True, null=True, verbose_name="Buổi")
    daylearn = models.DateField(verbose_name="Ngày học")
    timelearnstart = models.TimeField(null = True, blank=True,verbose_name="Thời gian học")
    timelearnend = models.TimeField(null = True, blank=True,verbose_name="Thời gian kết thúc")
    note = models.CharField(max_length=300, null = True, blank=True, verbose_name="Ghi chú")
    active = models.BooleanField(default=True, verbose_name="Trạng thái")
    
    def __str__(self):
        return  self.classname
    class Meta:
        ordering =["classname"]
        verbose_name_plural = "Lịch học theo lớp"

class CheckInClass(models.Model):
    id_student = models.IntegerField(default=0, blank=True, null=True, verbose_name="ID học viên")
    student = models.CharField(max_length=50, blank=True, null=True, verbose_name="Tên học viên")
    classname = models.CharField(max_length=50, blank=True, null=True, verbose_name="Tên lớp")
    dayname = models.CharField(max_length=50, blank=True, null=True, verbose_name="Buổi")
    daylearn = models.DateField(verbose_name="Ngày học")
    timelearnstart = models.TimeField(null = True, blank=True,verbose_name="Thời gian học")
    timelearnend = models.TimeField(null = True, blank=True,verbose_name="Thời gian kết thúc")
    note = models.CharField(max_length=300, null = True, blank=True, verbose_name="Ghi chú")
    active = models.BooleanField(default=True, verbose_name="Trạng thái")
    
    def __str__(self):
        return  self.student
    class Meta:
        ordering =["student"]
        verbose_name_plural = "Thời khóa biểu cá nhân"

class Notify(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True, verbose_name="Tiêu đề")
    content = models.CharField(max_length=1000, blank=True, null=True, verbose_name="Nội dung")
    create_date = models.DateField(auto_now_add=True, verbose_name="Ngày đăng")
    active = models.BooleanField(default=True, verbose_name="Trạng thái")

    def __str__(self):
        return  self.title
    class Meta:
        ordering =["title"]
        verbose_name_plural = "Thông báo"

home/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from .models import *

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','first_name','last_name','password1','password2','is_staff','is_superuser','is_active']

class CreateStudentForm(ModelForm):
    class Meta:
        model = Student
        fields = '__all__'

class UpdateStudentForm(ModelForm):
    class Meta:
        model = Student 
        fields = 'email','phonenumber','adress','phonenumber_family','fee','fee_remain','note','active'

class CreateClassnameForm(ModelForm):
    class Meta:
        model = Classname
        fields = '__all__'
        
class UpdateClassForm(ModelForm):
    class Meta:
        model = Classname
        fields = 'teacher','note','active'

class CreateTeacherForm(ModelForm):
    class Meta:
        model = Teacher
        fields = '__all__'
        
class UpdateTeacherForm(ModelForm):
    class Meta:
        model = Teacher
        fields = 'email','phonenumber','adress','note','active'

class CreateRoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'

class CreateAreaForm(ModelForm):
    class Meta:
        model = Area
        fields = '__all__'
        
class CreateNotifyForm(ModelForm):
    class Meta:
        model = Notify
        fields = '__all__'     

class CreateTimeShiftForm(ModelForm):
    class Meta:
        model = TimeShift
        fields = '__all__'

class CreateUnitForm(ModelForm):
    class Meta:
        model = Unit
        fields = '__all__'

home/templates/student/createDetailSchedule.html
{% extends "pages/base.html" %}
<!-- break -->
{% block title %}
<!-- Student -->
{% endblock title %}
<!-- break -->
{% block content %}
<!-- break -->
{% load static %}
<!-- break -->
<div class="card-header">
    <h2 class="text-center font-weight-light">Thời khóa biểu cá nhân</h2>
</div>
<div class="card-body">
    <div class="form-row">
        <div class="col-md-7">
            <div class="card-body" style="margin:0 auto; width: 100%;">
                <div id="calendar" style=" width: 100%; margin: 0 20px 20px 0;">
                </div>
            </div>
        </div>
        <div class="col-md-5">
            <div class="card-body" style="margin:0 auto; width: 100%;">
                <div>
                    <h2 class="text-center">Thông tin học viên</h2>
                </div>
                <div class="card-body" style="margin:0 auto; width: 100%;">
                    <div class="form-row">
                        <div class="col-md-4">
                            <label>
                                <h5>Họ và tên:</h5>
                            </label>
                        </div>
                        <div class="col-md-8">
                            <label>
                                <h5>{{ student.fullname }}</h5>
                            </label>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md-4">
                            <label>
                                <h5>Giới tính:</h5>
                            </label>
                        </div>
                        <div class="col-md-8">
                            <label>
                                <h5>{{ student.gender }}</h5>
                            </label>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md-4">
                            <label>
                                <h5>Ngày sinh:</h5>
                            </label>
                        </div>
                        <div class="col-md-8">
                            <label>
                                <h5>{{ student.birthday|date:"d-m-Y" }}</h5>
                            </label>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md-4">
                            <label>
                                <h5>Số điện thoại:</h5>
                            </label>
                        </div>
                        <div class="col-md-8">
                            <label>
                                <h5>{{ student.phonenumber }}</h5>
                            </label>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md-4">
                            <label>
                                <h5>Email:</h5>
                            </label>
                        </div>
                        <div class="col-md-8">
                            <label>
                                <h5>{{ student.email }}</h5>
                            </label>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md-4">
                            <label>
                                <h5>Địa chỉ:</h5>
                            </label>
                        </div>
                        <div class="col-md-8">
                            <label>
                                <h5>{{ student.adress }}</h5>
                            </label>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md-4">
                            <label>
                                <h5>Số điện thoại gia đình:</h5>
                            </label>
                        </div>
                        <div class="col-md-8">
                            <label>
                                <h5>{{ student.phonenumber_family }}</h5>
                            </label>
                        </div>
                    </div>
                </div>
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                        <!-- <label for="id_submit">Thời khóa biểu cá nhân cho {{student.fullname}} hiện chưa có</label> -->
                        <input class="btn btn-danger" type="submit" style="margin-left: auto; margin-right: auto;"
                            name="submit" id="id_submit" value="Xác nhận tạo thời khóa biểu cá nhân">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var initialLocaleCode = 'VI';
        var calendarEl = document.getElementById('calendar');

        var calendar = new FullCalendar.Calendar(calendarEl, {
            plugins: ['interaction', 'dayGrid'],
            header: {
                //left: 'prevYear,prev,next,nextYear today',
                //center: 'title',
                //right: 'dayGridMonth'
                right: 'today prev,next',
            },
            defaultDate: '{{ classname.startdate|date:"Y-m-d" }}',
            locale: initialLocaleCode,
            navLinks: true, // can click day/week names to navigate views
            //editable: true,
            eventLimit: true, // allow "more" link when too many events
            events: [
                {% for i in checkinclass %} 
                {% if student.fullname == i.student %}
                {
            title: '{{ i.dayname }}',
            start: '{{ i.daylearn|date:"Y-m-d" }}',
            end: '{{ i.daylearn|date:"Y-m-d" }}',
                    {% if i.active == 1 %}
    color: '#c5cae9',
        {% else %}
    color: '#bdbdbd'
    {% endif %}
                },
    {% endif %}
    {% endfor %}
            ],
        });
    calendar.render();
    });
</script>
<!-- break -->
{% endblock content %}

home/templates/student/detailStudent.html
{% extends "pages/base.html" %} {% block title %} Đăng kí học {% endblock title %} {% block content %} {% load static %}
<div class="card-header">
    <h2 class="text-center font-weight-light">Thay đổi thông tin học viên</h2>
</div>
<div class="card-body">
    <form method='POST' action="" id="qrcodeRedirectForm"  name="qrcodeRedirectForm">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-md-4">
                <label class="small mb-1" for="inputName">Họ và tên</label>
                <div class="form-group">
                    <input class="form-control" disabled id="inputName" type="text" placeholder="Nhập họ và tên"
                        value="{{ student.fullname }}" />
                </div>
            </div>
            <!-- ông thử link cách GET value của selectbox trong video này thử -->
            <!-- https://www.youtube.com/watch?v=Iiat5mc1Yz8 -->
            <div class="col-md-4">
                <label class="small mb-1" for="inputGender">Giới tính</label>
                <div class="form-group">
                    <input class="form-control" disabled id="inputGender" type="text" value="{{ student.gender }}" />
                </div>
            </div>
            <div class="col-md-4">
                <label class="small mb-1" for="inputBirthDay">Ngày sinh</label>
                <div class="form-group">
                    <input class="form-control" disabled id="inputBirthDay" type="date"
                        value="{{ student.birthday|date:"Y-m-d" }}" />
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="col-md-4">
                <label class="small mb-1" for="inputEmail">Email</label>
                <div class="form-group">
                    <input class="form-control" name="email" required id="id_email" type="email"
                        value="{{ student.email }}" />
                </div>
            </div>
            <div class="col-md-4">
                <label class="small mb-1" for="inputIdentityCard">CMND/Thẻ căn cước</label>
                <div class="form-group">
                    <input class="form-control" disabled id="inputIdentityCard" type="text"
                        placeholder="Nhập CMND học viên" value="{{ student.identity_card }}" />
                </div>
            </div>
            <div class="col-md-4">
                <label class="small mb-1" for="id_phonenumber">Số điện thoại</label>
                <div class="form-group">
                    <input class="form-control" name="phonenumber" required id="id_phonenumber" type="text"
                        placeholder="Nhập số điện thoại của học viên" value="{{ student.phonenumber }}" /></div>
            </div>
        </div>
        <div class="form-row">
            <div class="col-md-8">
                <label class="small mb-1" for="id_adress">Địa chỉ</label>
                <div class="form-group">
                    <input class="form-control" name="adress" required id="id_adress" type="text"
                        placeholder="Nhập địa chỉ của học viên " value="{{ student.adress }}" />
                </div>
            </div>
            <div class="col-md-4">
                <label class="small mb-1" for="id_phonenumber_family">Số điện thoại phụ huynh</label>
                <div class="form-group">
                    <input class="form-control" name="phonenumber_family" required id="id_phonenumber_family"
                        type="text" placeholder="Nhập số điện thoại phụ huynh"
                        value="{{ student.phonenumber_family }}" /></div>
            </div>
        </div>
        <div class="form-row">
            <!-- đây là listBox lấy dữ liệu từ dưới cơ sở dữ liệu bảng UNIT -->
            <div class="col-md-4">
                <label class="small mb-1" for="inputFirstName">Khóa học</label>
                <div class="form-group">
                    <select onchange="changeUnitClassname(this.value)" class="form-control" id="id_unit">
                        {% for i in classname %}
                        {% if i.pk == student.classname_id%}
                        <option value="{{i.unit_id}}" hidden>{{i.unit}}</option>
                        {% endif %}
                        {% endfor %}
                        {% for i in unit %}
                        {% if i.active %}
                        <option value="{{i.pk}}">{{i.fullname}}</option>
                        {% endif %}
                        {% endfor %}
                        <!-- <option value="1">AEngTu</option> -->
                    </select>
                </div>
            </div>
            <div class="col-md-4">
                <label class="small mb-1" for="inputClass">Lớp</label>
                <div class="form-group">
                    <select onchange="changeclassname()" class="form-control" id="id_classname" name="classname">
                        <option value="{{ student.classname_id }}" hidden>{{ student.classname }}</option>
                        {% for i in classname %}
                        {% if i.active == 0 %}
                        <option value="{{i.pk}}" data-option="{{i.unit_id}}">{{i.fullname}}</option>
                        {% endif %}
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="col-md-4">
                <label class="small mb-1" for="inputTeacherName">Giảng viên</label>
                <div class="form-group">
                    <select disabled class="form-control" id="id_teacher" required>
                        {% for i in classname %}
                        {% if i.pk == student.classname_id%}
                        <option value="{{i.pk}}" hidden>{{i.teacher}}</option>
                        {% endif %}
                        {% endfor %}
                        {% for i in classname %}
                        {% if i.active == 0 %}
                        <option value="{{i.pk}}" hidden>{{i.teacher}}</option>
                        {% endif %}
                        {% endfor %}
                    </select>
                </div>
            </div>
            <script>
                function changeclassname() {
                    var x = document.getElementById("id_classname").value;
                    document.getElementById("id_teacher").value = x;
                }
                var id_unit = document.querySelector('#id_unit');
                var id_classname = document.querySelector('#id_classname');
                var options_unit_classname = id_classname.querySelectorAll('option');

                function changeUnitClassname(selValue) {
                    id_classname.innerHTML = '';
                    for (var i = 0; i < options_unit_classname.length; i++) {
                        if (options_unit_classname[i].dataset.option === selValue) {
                            id_classname.appendChild(options_unit_classname[i]);
                        }
                    }
                    var x = document.getElementById("id_classname").value;
                    document.getElementById("id_teacher").value = x;
                }
                changeUnitClassname(id_unit.value);
            </script>
        </div>
        <div class="form-row">
            <div class="col-md-3">
                <label class="small mb-1" for="inputFee">Số tiền nộp</label>
                <div class="form-group input-group mb-3">
                    <input class="form-control" required id="id_fee" name="fee" type="text"
                        placeholder="Nhập số tiền mà học viên nộp vào đây" value="{{ student.fee }}" />
                    <div class="input-group-prepend">
                        <span class="input-group-text">VND</span>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <label class="small mb-1" for="inputFee">Số tiền còn thiếu</label>
                <div class="form-group input-group mb-3">
                    <input class="form-control" required id="id_fee_remain" name="fee_remain" type="text"
                        value="{{ student.fee_remain }}" />
                    <div class="input-group-prepend">
                        <span class="input-group-text">VND</span>
                    </div>
                </div>
            </div>
            <div class="col-md-5">
                <label class="small mb-1" for="inputNote">Ghi chú</label>
                <div class="form-group">
                    <input class="form-control" name="note" id="id_note" type="text" placeholder="Ghi chú"
                        value="{{ student.note }}" />
                </div>
            </div>
            <script>
            </script>
            <div class="col-md-1">
                <label class="small mb-1" for="inputActive">Trạng thái</label>
                <div class="form-group">
                    <!-- <input class="form-control" required id="inputNote" type="checkbox" placeholder="Ghi chú" /> -->
                    {% if student.active %}
                    <input type="checkbox" id="id_active" name="active" disabled checked data-toggle="toggle" value="1"
                        data-on="Học" data-off="Nghỉ" data-onstyle="success" data-offstyle="danger"> {% else %}
                    <input type="checkbox" id="id_active" name="active" data-toggle="toggle" value="0" data-on="Học"
                        data-off="Nghỉ" data-onstyle="success" data-offstyle="danger"> {% endif %}
                </div>
            </div>
        </div>
        <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
            <!-- <a class="btn btn-primary btn-block" href="login.html">Tạo tài khoản mới</a> -->
            {% if student.havedetailschedule == 0 %}
            <a onclick="submita()" id="id_button" class="btn btn-success"
                style="margin-left: auto; margin-right: auto; color: white;"><i class="fas fa-save"></i> Lưu</a>
            {% else %}
            <label class="btn btn-danger" onclick="alertnochange()" disabled
                style="margin-left: auto; margin-right: auto;">
                Không được thay đổi
            </label>
            {% endif %}
        </div>
    </form>
</div>

<script>
    function alertnochange() {
        swal("Lỗi", "Học viên này đã có thời khóa biểu cá nhân", "error", {
            buttons: false,
            timer: 1500,
        });
    }
    function submita() {
        swal("Great!!!", "Lưu thành công", "success", {
            buttons: false,
            timer: 1500,
        });
        setTimeout(function () {
            document.qrcodeRedirectForm.submit();
        }, 1500);
    }
</script>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<script src="{% static '/js/sweetalert.min.js' %}"></script>
<script src="{% static '/js/moment.min.js' %}"></script>
<script src="{% static '/js/jquery-3.4.1.min.js' %}"></script>
{% endblock content %}